---
title: "tpnoté_awa"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
  pdf_document:
    toc: true
---


```{r}
# Charger les bibliothèques nécessaires
library(dplyr)
library(readr)
library(ggplot2)
```




```{r}



# Fonction pour lire et filtrer les données de ventes à partir de plusieurs fichiers CSV
lire_donnees_ventes <- function(repertoire, date_debut, date_fin) {
  
  # Liste tous les fichiers CSV dans le répertoire spécifié
  liste_fichiers <- list.files(path = repertoire, pattern = "\\.csv$", full.names = TRUE)
  
  # Lecture des fichiers CSV, fusion des données et filtrage des dates
  donnees_ventes <- liste_fichiers %>%
    # Lire chaque fichier CSV avec read_csv et les combiner
    lapply(function(fichier) read_csv(fichier, show_col_types = FALSE, name_repair = "minimal")) %>%
    bind_rows() %>%  # Fusionner les données en une seule table
    filter(date >= as.Date(date_debut) & date <= as.Date(date_fin))  # Filtrer les lignes par plage de dates
  
  # Retourne les données combinées et filtrées
  return(donnees_ventes)
}



# Utiliser la fonction pour lire les fichiers
chemin_repertoire <- "C:/Users/dieye/Downloads/awasylla"
date_debut <- "2020-01-01"
date_fin <- "2024-12-31"

donnees_ventes <- lire_donnees_ventes(chemin_repertoire, date_debut, date_fin)

donnees_ventes

```


```{r}
ggplot(donnees_ventes, aes(x = date, y = nb_de_ventes)) +
  geom_line(color = "purple") +
  labs(
    title = "Évolution des ventes au fil des années",
    x = "Date",
    y = "Nombre de ventes"
    
  ) +
  theme_minimal()
```


